from enum import IntEnum, unique


@unique
class AnalysisStatus(IntEnum):
    BEFORE_RECEIVING = 000

    PROCESSING = 100
    REQUESTING_TO_REPO = 110
    INITIALIZING_AI = 120
    WAITING_AI = 121
    LEARNING_DATA = 122
    GENERATING_ANSWER = 130
    GENERATING_README = 131
    JUDGING_COMMITS = 132
    SCORING_COMMITS = 133
    FINISHING = 140
    RESETTING_LEARNED_DATA = 141

    DONE = 200

    ERROR = 300
    REPO_TOKEN_ERROR = 310
    GITHUB_ACCESS_TOKEN_INVALID = 311
    GITLAB_PRIVATE_TOKEN_INVALID = 312
    REPO_REQUEST_FAILED = 320
    INSUFFICIENT_GITHUB_REQUEST = 321
    INSUFFICIENT_GITLAB_REQUEST = 322
    REPO_REQUEST_TIMEOUT = 323

    PERCENTAGES: dict['AnalysisStatus', int] = {
        BEFORE_RECEIVING: 0,
        REQUESTING_TO_REPO: 10,
        WAITING_AI: 25,
        LEARNING_DATA: 30,
        GENERATING_README: 50,
        JUDGING_COMMITS: 60,
        SCORING_COMMITS: 80,
        RESETTING_LEARNED_DATA: 90,
        DONE: 100
    }
