from enum import IntEnum, unique


@unique
class AnalysisStatus(IntEnum):
    BEFORE_RECEIVING = 000

    PROCESSING = 100
    REQUESTING_TO_REPO = 110
    CHECKING_FOR_REQUESTING = 111
    REQUESTING_CONTENT = 112
    REQUESTING_COMMITS = 113
    INITIALIZING_AI = 120
    WAITING_AI = 121
    LEARNING_DATA = 122
    GENERATING_ANSWER = 130
    GENERATING_README = 131
    JUDGING_COMMITS = 132
    SCORING_COMMITS = 133
    FINISHING = 140
    RESETTING_LEARNED_DATA = 141

    DONE = 200

    ERROR = 300
    COA_ERROR = 310
    NO_REDIS_OBJECT = 311
    INTERNAL_SERVER_ERROR = 312
    REPO_TOKEN_ERROR = 320
    GITHUB_ACCESS_TOKEN_INVALID = 321
    GITLAB_PRIVATE_TOKEN_INVALID = 322
    REPO_REQUEST_FAILED = 330
    INSUFFICIENT_GITHUB_REQUEST = 331
    INSUFFICIENT_GITLAB_REQUEST = 332
    REPO_REQUEST_TIMEOUT = 333


AnalysisPercentages: dict[AnalysisStatus, int] = {
    AnalysisStatus.BEFORE_RECEIVING: 0,
    AnalysisStatus.CHECKING_FOR_REQUESTING: 5,
    AnalysisStatus.REQUESTING_CONTENT: 10,
    AnalysisStatus.REQUESTING_COMMITS: 20,
    AnalysisStatus.WAITING_AI: 25,
    AnalysisStatus.LEARNING_DATA: 30,
    AnalysisStatus.GENERATING_README: 50,
    AnalysisStatus.JUDGING_COMMITS: 60,
    AnalysisStatus.SCORING_COMMITS: 80,
    AnalysisStatus.RESETTING_LEARNED_DATA: 90,
    AnalysisStatus.DONE: 100
}
