from enum import IntEnum


class AnalysisStatus(IntEnum):
    BEFORE_RECEIVING = 000

    PROCESSING = 100
    REQUESTING_TO_REPO = 110
    REQUESTING_TO_GITHUB = 111
    REQUESTING_TO_GITLAB = 112
    LEARNING = 120
    LEARNING_DATA = 121
    GENERATING_ANSWER = 130
    GENERATING_README = 131
    JUDGING_COMMITS = 132
    SCORING_COMMITS = 133
    FINISHING = 140
    RESETTING_LEARNED_DATA = 141

    DONE = 200

    ERROR = 300
    REPO_TOKEN_ERROR = 310
    GITHUB_ACCESS_TOKEN_INVALID = 311
    GITLAB_PRIVATE_TOKEN_INVALID = 312
    REPO_REQUEST_FAILED = 320
    INSUFFICIENT_GITHUB_REQUEST = 321
    INSUFFICIENT_GITLAB_REQUEST = 322
    REPO_REQUEST_TIMEOUT = 323